baseurl = "http://www.example.com"
title = "My site"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Mikael Falkenberg Krog"
  info = "Software developer"
  description = "My personal website"
  #keywords = "blog,developer,personal"
  avatarurl = "images/Self-portrait.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  custom_css= ["css/styles.css"]

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mikaelfk"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/Mikaelfk"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/mikael-falkenberg-krog-a1b5b3237/"

# Menu links
[[menu.main]]
	name = "CV"
	weight = 1
	url = "cv/"
